Fail
file path is :
projects/deltachat-core/rust/src/contact.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/projects/deltachat-core/rust)
error[E0252]: the name `Result` is defined multiple times
  --> src/contact.rs:15:42
   |
5  | use anyhow::Result;
   |     -------------- previous import of the type `Result` here
...
15 | use anyhow::{bail, ensure, Context as _, Result};
   |                                          ^^^^^^ `Result` reimported here
   |
   = note: `Result` must be defined only once in the type namespace of this module

error[E0432]: unresolved import `crate::Context`
 --> src/contact.rs:6:5
  |
6 | use crate::Context;
  |     ^^^^^^^^^^^^^^ no `Context` in the root
  |
help: a similar name exists in the module
  |
6 | use crate::context;
  |            ~~~~~~~
help: consider importing one of these items instead
  |
6 | use anyhow::Context;
  |     ~~~~~~~~~~~~~~~
6 | use core::task::Context;
  |     ~~~~~~~~~~~~~~~~~~~
6 | use crate::context::Context;
  |     ~~~~~~~~~~~~~~~~~~~~~~~
6 | use exif::Context;
  |     ~~~~~~~~~~~~~
    and 2 other candidates

error[E0432]: unresolved import `crate::ContactId`
 --> src/contact.rs:7:5
  |
7 | use crate::ContactId;
  |     ^^^^^^^---------
  |     |      |
  |     |      help: a similar name exists in the module: `contact`
  |     no `ContactId` in the root

error[E0425]: cannot find value `DC_CONTEXT_MAGIC` in this scope
    --> src/contact.rs:1265:31
     |
1265 |     if context.inner.magic != DC_CONTEXT_MAGIC || contact_id <= DC_CONTACT_ID_LAST_SPECIAL {
     |                               ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_CONTACT_ID_LAST_SPECIAL` in this scope
    --> src/contact.rs:1265:65
     |
1265 |     if context.inner.magic != DC_CONTEXT_MAGIC || contact_id <= DC_CONTACT_ID_LAST_SPECIAL {
     |                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SQLITE_ROW` in this scope
    --> src/contact.rs:1275:48
     |
1275 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_ROW || sqlite3_column_int(stmt.as_mut().unwrap(), 0) >= 1 {
     |                                                ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SQLITE_ROW` in this scope
    --> src/contact.rs:1286:48
     |
1286 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_ROW || sqlite3_column_int(stmt.as_mut().unwrap(), 0) >= 1 {
     |                                                ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SQLITE_DONE` in this scope
    --> src/contact.rs:1296:48
     |
1296 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_DONE {
     |                                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_EVENT_CONTACTS_CHANGED` in this scope
    --> src/contact.rs:1300:24
     |
1300 |     context.emit_event(DC_EVENT_CONTACTS_CHANGED, 0, 0);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

warning: unused import: `std::sync::Arc`
 --> src/contact.rs:4:5
  |
4 | use std::sync::Arc;
  |     ^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:6:5
  |
6 |     unused,
  |     ^^^^^^
  = note: `#[warn(unused_imports)]` implied by `#[warn(unused)]`

warning: unused import: `Result`
  --> src/contact.rs:15:42
   |
15 | use anyhow::{bail, ensure, Context as _, Result};
   |                                          ^^^^^^

error[E0609]: no field `magic` on type `Arc<InnerContext>`
    --> src/contact.rs:1265:22
     |
1265 |     if context.inner.magic != DC_CONTEXT_MAGIC || contact_id <= DC_CONTACT_ID_LAST_SPECIAL {
     |                      ^^^^^ unknown field
     |
     = note: available fields are: `blobdir`, `sql`, `smeared_timestamp`, `generating_key_mutex`, `oauth2_mutex` ... and 17 others

error[E0599]: no method named `prepare` found for struct `Sql` in the current scope
    --> src/contact.rs:1271:35
     |
1271 |     stmt = Some(context.inner.sql.prepare(
     |                 ------------------^^^^^^^ method not found in `Sql`
     |
    ::: src/sql.rs:57:1
     |
57   | pub struct Sql {
     | -------------- method `prepare` not found for this struct
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
             candidate #1: `precis_core::profile::Profile`
             candidate #2: `precis_core::profile::PrecisFastInvocation`

error[E0425]: cannot find function `sqlite3_step` in this scope
    --> src/contact.rs:1275:8
     |
1275 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_ROW || sqlite3_column_int(stmt.as_mut().unwrap(), 0) >= 1 {
     |        ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_column_int` in this scope
    --> src/contact.rs:1275:62
     |
1275 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_ROW || sqlite3_column_int(stmt.as_mut().unwrap(), 0) >= 1 {
     |                                                              ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_finalize` in this scope
    --> src/contact.rs:1278:5
     |
1278 |     sqlite3_finalize(stmt.as_mut().unwrap());
     |     ^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `prepare` found for struct `Sql` in the current scope
    --> src/contact.rs:1281:35
     |
1281 |     stmt = Some(context.inner.sql.prepare(
     |                 ------------------^^^^^^^ method not found in `Sql`
     |
    ::: src/sql.rs:57:1
     |
57   | pub struct Sql {
     | -------------- method `prepare` not found for this struct
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
             candidate #1: `precis_core::profile::Profile`
             candidate #2: `precis_core::profile::PrecisFastInvocation`

error[E0425]: cannot find function `sqlite3_step` in this scope
    --> src/contact.rs:1286:8
     |
1286 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_ROW || sqlite3_column_int(stmt.as_mut().unwrap(), 0) >= 1 {
     |        ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_column_int` in this scope
    --> src/contact.rs:1286:62
     |
1286 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_ROW || sqlite3_column_int(stmt.as_mut().unwrap(), 0) >= 1 {
     |                                                              ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_finalize` in this scope
    --> src/contact.rs:1289:5
     |
1289 |     sqlite3_finalize(stmt.as_mut().unwrap());
     |     ^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `prepare` found for struct `Sql` in the current scope
    --> src/contact.rs:1292:35
     |
1292 |     stmt = Some(context.inner.sql.prepare(
     |                 ------------------^^^^^^^ method not found in `Sql`
     |
    ::: src/sql.rs:57:1
     |
57   | pub struct Sql {
     | -------------- method `prepare` not found for this struct
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
             candidate #1: `precis_core::profile::Profile`
             candidate #2: `precis_core::profile::PrecisFastInvocation`

error[E0425]: cannot find function `sqlite3_step` in this scope
    --> src/contact.rs:1296:8
     |
1296 |     if sqlite3_step(stmt.as_mut().unwrap()) != SQLITE_DONE {
     |        ^^^^^^^^^^^^ not found in this scope

error[E0061]: this method takes 1 argument but 3 arguments were supplied
    --> src/contact.rs:1300:13
     |
1300 |     context.emit_event(DC_EVENT_CONTACTS_CHANGED, 0, 0);
     |             ^^^^^^^^^^                            -  - unexpected argument of type `{integer}`
     |                                                   |
     |                                                   unexpected argument of type `{integer}`
     |
note: method defined here
    --> src/context.rs:595:12
     |
595  |     pub fn emit_event(&self, event: EventType) {
     |            ^^^^^^^^^^        ----------------
help: remove the extra arguments
     |
1300 -     context.emit_event(DC_EVENT_CONTACTS_CHANGED, 0, 0);
1300 +     context.emit_event(DC_EVENT_CONTACTS_CHANGED);
     |

error[E0599]: no method named `prepare` found for struct `sql::Sql` in the current scope
    --> src/contact.rs:1271:35
     |
1271 |     stmt = Some(context.inner.sql.prepare(
     |                 ------------------^^^^^^^ method not found in `sql::Sql`
     |
    ::: src/sql.rs:57:1
     |
57   | pub struct Sql {
     | -------------- method `prepare` not found for this struct
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
             candidate #1: `precis_core::profile::Profile`
             candidate #2: `precis_core::profile::PrecisFastInvocation`

error[E0599]: no method named `prepare` found for struct `sql::Sql` in the current scope
    --> src/contact.rs:1281:35
     |
1281 |     stmt = Some(context.inner.sql.prepare(
     |                 ------------------^^^^^^^ method not found in `sql::Sql`
     |
    ::: src/sql.rs:57:1
     |
57   | pub struct Sql {
     | -------------- method `prepare` not found for this struct
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
             candidate #1: `precis_core::profile::Profile`
             candidate #2: `precis_core::profile::PrecisFastInvocation`

error[E0599]: no method named `prepare` found for struct `sql::Sql` in the current scope
    --> src/contact.rs:1292:35
     |
1292 |     stmt = Some(context.inner.sql.prepare(
     |                 ------------------^^^^^^^ method not found in `sql::Sql`
     |
    ::: src/sql.rs:57:1
     |
57   | pub struct Sql {
     | -------------- method `prepare` not found for this struct
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
             candidate #1: `precis_core::profile::Profile`
             candidate #2: `precis_core::profile::PrecisFastInvocation`

Some errors have detailed explanations: E0061, E0252, E0425, E0432, E0599, E0609.
For more information about an error, try `rustc --explain E0061`.
warning: `deltachat` (lib) generated 2 warnings
error: could not compile `deltachat` (lib) due to 21 previous errors; 2 warnings emitted
warning: build failed, waiting for other jobs to finish...
warning: `deltachat` (lib test) generated 2 warnings (2 duplicates)
error: could not compile `deltachat` (lib test) due to 21 previous errors; 2 warnings emitted
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

