Fail
file path is :
projects/deltachat-core/rust/src/location.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/projects/deltachat-core/rust)
error[E0433]: failed to resolve: use of undeclared type `RunningState`
   --> src/location.rs:351:52
    |
351 |     if context.inner.running_state.read().await == RunningState::Stopped {
    |                                                    ^^^^^^^^^^^^ use of undeclared type `RunningState`
    |
note: enum `crate::context::RunningState` exists but is inaccessible
   --> src/context.rs:299:1
    |
299 | enum RunningState {
    | ^^^^^^^^^^^^^^^^^ not accessible

error[E0425]: cannot find value `DC_CONTACT_ID_SELF` in this scope
   --> src/location.rs:382:29
    |
382 | ...                   DC_CONTACT_ID_SELF
    |                       ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `continue_streaming` in this scope
   --> src/location.rs:392:8
    |
392 |     if continue_streaming {
    |        ^^^^^^^^^^^^^^^^^^
    |
help: the binding `continue_streaming` is available in a different scope in the same function
   --> src/location.rs:366:25
    |
366 |                 let mut continue_streaming = false;
    |                         ^^^^^^^^^^^^^^^^^^

error[E0425]: cannot find value `DC_CONTACT_ID_SELF` in this scope
   --> src/location.rs:393:44
    |
393 |         context.emit_location_changed(Some(DC_CONTACT_ID_SELF));
    |                                            ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `continue_streaming` in this scope
   --> src/location.rs:397:8
    |
397 |     Ok(continue_streaming)
    |        ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0728]: `await` is only allowed inside `async` functions and blocks
   --> src/location.rs:367:45
    |
365 |             |mut rows| {
    |             ---------- this is not `async`
366 |                 let mut continue_streaming = false;
367 |                 while let row = rows.next().await? {
    |                                             ^^^^^ only allowed inside `async` functions and blocks

error[E0616]: field `running_state` of struct `InnerContext` is private
   --> src/location.rs:351:22
    |
351 |     if context.inner.running_state.read().await == RunningState::Stopped {
    |                      ^^^^^^^^^^^^^ private field

error[E0599]: no function or associated item named `new` found for trait `rusqlite::Params`
   --> src/location.rs:360:31
    |
360 |             rusqlite::Params::new(time()),
    |                               ^^^ function or associated item not found in `Params`

error[E0599]: no method named `prepare` found for struct `Sql` in the current scope
   --> src/location.rs:372:25
    |
369 |                       let stmt_insert = context
    |  _______________________________________-
370 | |                        .inner
371 | |                        .sql
372 | |                        .prepare(
    | |                        -^^^^^^^ method not found in `Sql`
    | |________________________|
    | 
    |
   ::: src/sql.rs:57:1
    |
57  |   pub struct Sql {
    |   -------------- method `prepare` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
            candidate #1: `precis_core::profile::Profile`
            candidate #2: `precis_core::profile::PrecisFastInvocation`

error[E0599]: no function or associated item named `new` found for trait `rusqlite::Params`
   --> src/location.rs:376:43
    |
376 |                         rusqlite::Params::new(
    |                                           ^^^ function or associated item not found in `Params`

error[E0599]: no method named `interrupt_location` found for reference `&context::Context` in the current scope
   --> src/location.rs:394:17
    |
394 |         context.interrupt_location();
    |                 ^^^^^^^^^^^^^^^^^^ method not found in `&Context`
    |
help: one of the expressions' fields has a method of the same name
    |
394 |         context.inner.scheduler.interrupt_location();
    |                 ++++++++++++++++
help: one of the expressions' fields has a method of the same name
    |
394 |         context.scheduler.interrupt_location();
    |                 ++++++++++

error[E0599]: no method named `prepare` found for struct `sql::Sql` in the current scope
   --> src/location.rs:372:25
    |
369 |                       let stmt_insert = context
    |  _______________________________________-
370 | |                        .inner
371 | |                        .sql
372 | |                        .prepare(
    | |                        -^^^^^^^ method not found in `sql::Sql`
    | |________________________|
    | 
    |
   ::: src/sql.rs:57:1
    |
57  |   pub struct Sql {
    |   -------------- method `prepare` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
            candidate #1: `precis_core::profile::Profile`
            candidate #2: `precis_core::profile::PrecisFastInvocation`

Some errors have detailed explanations: E0425, E0433, E0599, E0616, E0728.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `deltachat` (lib) due to 11 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `deltachat` (lib test) due to 11 previous errors
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

