Fail
file path is :
projects/deltachat-core/rust/src/context.rs

output is:


error is :
    Blocking waiting for file lock on package cache
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/RustRepoTrans/projects/deltachat-core/rust)
error[E0425]: cannot find value `DC_CONTEXT_MAGIC` in this scope
   --> src/context.rs:672:28
    |
672 |     if self.inner.magic != DC_CONTEXT_MAGIC {
    |                            ^^^^^^^^^^^^^^^^ not found in this scope

error[E0609]: no field `magic` on type `Arc<InnerContext>`
   --> src/context.rs:672:19
    |
672 |     if self.inner.magic != DC_CONTEXT_MAGIC {
    |                   ^^^^^ unknown field
    |
    = note: available fields are: `blobdir`, `sql`, `smeared_timestamp`, `running_state`, `generating_key_mutex` ... and 19 others

error[E0599]: no method named `has_ongoing` found for struct `Arc<InnerContext>` in the current scope
   --> src/context.rs:676:19
    |
676 |     if self.inner.has_ongoing().await? {
    |                   ^^^^^^^^^^^ method not found in `Arc<InnerContext>`

error[E0599]: no method named `log_warning` found for struct `Arc<InnerContext>` in the current scope
   --> src/context.rs:677:20
    |
677 |         self.inner.log_warning(0, "There is already another ongoing process running.");
    |                    ^^^^^^^^^^^ method not found in `Arc<InnerContext>`

error[E0609]: no field `shall_stop_ongoing` on type `Arc<InnerContext>`
   --> src/context.rs:684:16
    |
684 |     self.inner.shall_stop_ongoing = false;
    |                ^^^^^^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `blobdir`, `sql`, `smeared_timestamp`, `running_state`, `generating_key_mutex` ... and 19 others

Some errors have detailed explanations: E0425, E0599, E0609.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `deltachat` (lib) due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `deltachat` (lib test) due to 5 previous errors
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

