Fail
file path is :
projects/deltachat-core/rust/src/tools.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/projects/deltachat-core/rust)
error[E0599]: no method named `write_all` found for struct `tokio::fs::File` in the current scope
   --> src/tools.rs:404:16
    |
404 |     match file.write_all(buf).await {
    |                ^^^^^^^^^ method not found in `File`
    |
   ::: /home/k/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/io/util/async_write_ext.rs:369:12
    |
369 |         fn write_all<'a>(&'a mut self, src: &'a [u8]) -> WriteAll<'a, Self>
    |            --------- the method is available for `tokio::fs::File` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
6   + use tokio::io::AsyncWriteExt;
    |

error[E0599]: no method named `set_last_error` found for struct `Arc<InnerContext>` in the current scope
   --> src/log.rs:44:14
    |
44  |           $ctx.set_last_error(&formatted);
    |                ^^^^^^^^^^^^^^ method not found in `Arc<InnerContext>`
    |
   ::: src/tools.rs:407:13
    |
407 | /             error!(
408 | |                 context.inner,
409 | |                 "Cannot write {} bytes to \"{}\".", buf.len(), path_ref.display()
410 | |             );
    | |_____________- in this macro invocation
    |
    = note: this error originates in the macro `error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `emit_event` found for struct `Arc<InnerContext>` in the current scope
   --> src/log.rs:45:14
    |
45  |           $ctx.emit_event($crate::EventType::Error(formatted));
    |                ^^^^^^^^^^ method not found in `Arc<InnerContext>`
    |
   ::: src/tools.rs:407:13
    |
407 | /             error!(
408 | |                 context.inner,
409 | |                 "Cannot write {} bytes to \"{}\".", buf.len(), path_ref.display()
410 | |             );
    | |_____________- in this macro invocation
    |
    = note: this error originates in the macro `error` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0599`.
error: could not compile `deltachat` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `deltachat` (lib test) due to 3 previous errors
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

